### ISSUE TITLE
Why is it required to use a private key with a passphrase when the key can be encrypted

### ISSUE THREAD

**Issue by gdamjan** [certonid/certonid#5]
Seems to me that just encrypting the private key with KMS should be enough - why does the wiki insist on "(IMPORTANT! Key should contain passphrase. Certonid not support keys without passphrase)"?

**Comment by le0pard** [comment]
Because serverless component expected to `ParseEncryptedPrivateKey` with password. KMS/symmetric key encryption is optional, but passphrase - required. @gdamjan
