### ISSUE TITLE
Add link to article written in English

### ISSUE THREAD

**Issue by nzbart** [certonid/certonid#6]
I tracked down this article that it appears you wrote and is more accessible to those that don't read Russian:

* [Certonid — the SSH Certificate Authority Deployed on AWS Lambda](https://blog.mailtrap.io/certonid/)

Maybe add this to the list of articles in the project readme?

**Comment by le0pard** [comment]
Thanks @nzbart Fixed by https://github.com/certonid/certonid/commit/d5eeb75d483a3e5257e0d0ea9eb9bd04f3848500
